sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends dvipng latex2html latex-xcolor texlive texlive-base texlive-binaries texlive-extra-utils texlive-fonts-extra texlive-fonts-recommended texlive-font-utils texlive-lang-german texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-pstricks texlive texlive-base psutils
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build toki-pona-lessons_en.tex
- "./make_booklet.sh"
deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - _build/toki-pona-lessons_en.pdf
  - _build/toki-pona-lessons_en-booklet.pdf
  - _build/toki-pona-dictionary.pdf
  - _build/toki-pona_english.txt
  - _build/toki-pona-lessons_de

  skip_cleanup: true
  on:
tags: true
